// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33vSLVBZJXEf86FIVMpsedtSIGehXxHg',
    appId: '1:89090094536:web:e2e0997853e65a19ccbcfd',
    messagingSenderId: '89090094536',
    projectId: 'arabeia',
    authDomain: 'arabeia.firebaseapp.com',
    storageBucket: 'arabeia.appspot.com',
    measurementId: 'G-SG8BKGY0HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQE2-dzKhzM3NrMshCA9MidcqbxHohYs',
    appId: '1:89090094536:android:6d757bc9bde98922ccbcfd',
    messagingSenderId: '89090094536',
    projectId: 'arabeia',
    storageBucket: 'arabeia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1Eye3yJ0yOdy7u8wZUKahY9EVdOS9H4',
    appId: '1:89090094536:ios:b98a52a2e7c35e34ccbcfd',
    messagingSenderId: '89090094536',
    projectId: 'arabeia',
    storageBucket: 'arabeia.appspot.com',
    iosClientId: '89090094536-nlrcmk29kikegnbbqg15us4fvtgq7pjn.apps.googleusercontent.com',
    iosBundleId: 'ly.manassa.ly.arabeiaWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL1Eye3yJ0yOdy7u8wZUKahY9EVdOS9H4',
    appId: '1:89090094536:ios:c4df722ba6dea5e8ccbcfd',
    messagingSenderId: '89090094536',
    projectId: 'arabeia',
    storageBucket: 'arabeia.appspot.com',
    iosClientId: '89090094536-vr8uhea22r6fsuu87monij4ttm0oa01m.apps.googleusercontent.com',
    iosBundleId: 'ly.manassa.ly.arabeiaWebsite.RunnerTests',
  );
}
